# Generated by Django 4.1.7 on 2023-03-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anemone',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coral',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shark',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
