# Generated by Django 4.1.7 on 2023-03-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0002_anemone_description_coral_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='species_images/'),
        ),
        migrations.AlterField(
            model_name='coral',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='species_images/'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='species_images/'),
        ),
        migrations.AlterField(
            model_name='shark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='species_images/'),
        ),
    ]
